baseURL = 'https://ks1019.github.io/'
languageCode = 'en-us'
title = 'Kotaro Suto'
theme = 'anubis'
enableRobotsTXT = true
defaultContentLanguage = 'en-us'

[params]
author = 'Kotaro Suto'
description = 'Kotaro Suto Portfolio'
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto-without-switcher"
disableSummary = true

[[params.social]]
  id = "github"
  name = "ks1019"
[[params.social]]
  id = "twitter"
  name = "kotarong1"
[[params.social]]
  id = "linkedin"
  name = "kotarosuto"

[frontmatter]
  lastmod = ['lastmod', ':fileModTime', ':default']

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[markup.goldmark.renderer]
unsafe = true

[languages]
  [languages.en]
    languageCode = 'en-us'
  [languages.ja]
    languageCode = 'ja'
    title = 'ポートフォリオ'
    weight = 2
